### ISSUE TITLE
Install keystone/unicorn from pypi?

### ISSUE THREAD

**Issue by f0rki** [zardus/ctf-tools#122]
So keystone and unicorn are on pypi now. Currently they're built from git master. Should we switch to `pip install (keystone|unicorn)` and install the stable versions? 

capstone is already installed from pypi.

**Comment by zardus** [comment]
Yeah, I think that'd make sense. As the python packaging of these guys becomes more stable, it'll be much easier pulling them in through pip.

**Comment by f0rki** [comment]
OK. pull request incoming soon ;)

**Comment by zardus** [comment]
:+1:

**Comment by raildex1** [comment]
@zardus @f0rki can we revert back instead? On 14.04 this breaks unicorn install since qemu builds within the python 3 virtualenv can't compile.

As a result unicorn can't install, and pwndbg can't either.

As a compromise the python2 virtualenv works fine. It's just python3 which causes the issue.

The solution is simply use the older method of installing until this is somehow sorted from the pypi side if it's possible.

Keystone works fine and can stay as is.
