### ISSUE TITLE
Warning: cannot find svn location for apsw==3.8.6-r1

### ISSUE THREAD

**Issue by lv7777** [zardus/ctf-tools#68]
I tried install ctf-tools on kali linux,but error occurred in this command

```
 ./manage-tools setup
```

this behave is not changed when using sudo.

please tell me why this error occurred.

thanks.

**Comment by lv7777** [comment]
error occurred, but I can running `manage-tools`command.
So this issue is roughly solved.

thanks.

**Comment by zardus** [comment]
Could you post your system details (i.e., distro version and so forth) so we can try to track down the error?

**Comment by raildex1** [comment]
root@kali:~/ctf-tools/bin# ./manage-tools setup
No LSB modules are available.
dpkg-query: no packages found matching texinfo
dpkg-query: no packages found matching virtualenvwrapper
TOOLS | SETUP | Please install the following packages: build-essential libtool g++ gcc texinfo curl wget automake autoconf python python-dev git subversion unzip virtualenvwrapper
TOOLS | SETUP | Certain tools need i386 libraries (enable with 'dpkg --add-architecture i386; apt-get update').

#### Creating python2 virtualenv 'ctftools'

/root/ctf-tools/bin/ctf-tools-pip: line 33: virtualenv: command not found

I'm assuming the error he's talking about is similar to this @zardus 

(EDIT - Fix for above was simple on Kali - just run 
./manage-tools -s setup
)
On Kali 2016.1 Rolling edition.
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

If he's referring to the pip then 

https://lgogua.blogspot.com/2014/01/pip-list-error-correction-for-python-in.html

According to that blog updating pip solves the issue (maybe he's running an older version of Kali or something got corrupted - Kali starts playing up when you start messing around with it such as installing different versions on tools on one system).

pip install --upgrade distribute

In my case - I had to edit the ctf-tools-pip script and edit line 33 to - 

virtualenv -p "$PY_INTERPRETER"  "$VE_DIR"

removing  --system-site-packages since Kali seems to not play nice with it.
Will play around a bit to make sure nothing breaks because of it.

^^Obviously above allowed successful manage-tools setup but since site packages aren't shared everything else failed.

EDIT - for Kali Python library isn't stored at /lib/python2.7/
its at /usr/local/lib/python2.7/

The error is caused because of  /lib/python2.7/site-packages not existing.

Most tools still work fine - some packages in the kali repo just fail since they look for /lib/python2.7/site-packages so some tools like angr won't install. 

But Kali is a pentesting distro anyways and is designed to work with hundreds of tools at hence why the default stuff isn't where it should be.
