### ISSUE TITLE
ctf-tools can't update existing installs

### ISSUE THREAD

**Issue by crowell** [zardus/ctf-tools#7]
something like

`manage-tools upgrade` to update to the latest version of tools would be really awesome. Some things like `afl-fuzz` and `radare2` update very frequently, and keeping in sync would be helpful.

**Comment by zardus** [comment]
We could do an upgrade script, but what about just reinstalling it? Do you think that's inadequate?

**Comment by crowell** [comment]
reinstalling would be adequate, but it'd be nice to have a db or something that remembers what is already installed. This is the use case like `apt-get dist-upgrade` where I don't have to remember every package is installed on my machine.

**Comment by zardus** [comment]
First step, for single packages: 787e6e8990b3d96f3a2db87142923c5dbe6fbeb5

It's a bit tricky to check versions. The best I can think of is to hash the install script and override git to track the checked out commit of each package, and do upgrades based on that. Seems like a lot of work, though :-)

**Comment by f0rki** [comment]
What about a `manage-tools reinstall --all`, which just reinstalls every tool that was previously installed?

**Comment by zardus** [comment]
`manage-tools` already treats `all` specially:

```
if [ "$TOOL" == "all" ]
then
        for t in $($0 list)
        do
                $0 $ACTION $t
        done
```

So `manage-tools reinstall all` will reinstall *all* tools (not quite what we want). We could add a similar special handling for `installed`, so that `manage-tools reinstall installed` or `manage-tools uninstall installed` or so on will act on every installed tool. I think that would be super useful.
